apiVersion: v1
kind: Service
metadata:
  name: {{ include "streamlit-app.fullname" . }}
  labels:
    {{- include "streamlit-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8501
  selector:
    app: {{ include "streamlit-app.name" . }}
