apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamlit-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: streamlit
  template:
    metadata:
      labels:
        app: streamlit
    spec:
      containers:
      - name: streamlit
        image: saurabhkambli/streamlitapp:latest
        ports:
        - containerPort: 8501
      imagePullSecrets:
      - name: myregistrykey

    # spec:
    #   containers:
    #   - name: streamlit
    #     image: streamlitimage.azurecr.io/streamlitapp
    #     ports:
    #     - containerPort: 8501
    #   imagePullSecrets:
    #   - name: acr-secret
