replicaCount: 1

image:
  repository: saurabhkambli/streamlitapp
  pullPolicy: Always
  tag: "latest"

service:
  type: LoadBalancer
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths: []

nodeSelector: {}
tolerations: []
affinity: {}
